### ISSUE TITLE
Enabling Nitrate interferes with No Pylon Restrictions mod

### ISSUE THREAD

**Issue by Kanarisky** [terraria-catalyst/nitrate-mod#47]
### Description

When using the [No Pylon Restrictions mod by Jake](https://steamcommunity.com/sharedfiles/filedetails/?id=2812377597), you can use the fullscreen map to teleport to a pylon from anywhere.

However, when I try this with Nitrate enabled, I must all of a sudden have a pylon on-screen to be able to teleport. When they are off-screen, they are faded on the map, and I get the pylon out of range message from vanilla when I try to teleport to any. When one is on-screen, I can teleport to any pylon.

If I disable Nitrate I can use pylons from anywhere, as before.

**Comment by steviegt6** [comment]
Addressed in the next update.
